#include "mediamtxmanager.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QStandardPaths>
#include <QTextStream>
#include <QDebug>

// ─────────────────────────────────────────────────────────────────────────────
MediaMtxManager::MediaMtxManager(QObject *parent)
    : QObject(parent)
{
}

MediaMtxManager::~MediaMtxManager()
{
    stop();
}

// ─────────────────────────────────────────────────────────────────────────────
void MediaMtxManager::setMediaMtxPath(const QString &path) { m_mediaMtxPath = path; }
void MediaMtxManager::setRtspPort(quint16 port)           { m_rtspPort = port; }
void MediaMtxManager::setRtspPath(const QString &path)    { m_rtspPath = path; }

void MediaMtxManager::setReadCredentials(const QString &user, const QString &pass)
{
    m_readUser = user;
    m_readPass = pass;
}

void MediaMtxManager::setPublishCredentials(const QString &user, const QString &pass)
{
    m_pubUser = user;
    m_pubPass = pass;
}

bool MediaMtxManager::isRunning() const
{
    return m_process && m_process->state() == QProcess::Running;
}

QString MediaMtxManager::lastError() const { return m_lastError; }

// ─────────────────────────────────────────────────────────────────────────────
bool MediaMtxManager::start()
{
    if (isRunning()) return true;

    const QString binary = m_mediaMtxPath.isEmpty() ? findMediaMtxBinary() : m_mediaMtxPath;
    if (binary.isEmpty()) {
        m_lastError = "mediamtx binary not found. Place mediamtx.exe next to the application.";
        return false;
    }

    m_configPath = writeConfigFile();
    if (m_configPath.isEmpty()) {
        m_lastError = "Failed to write MediaMTX config file.";
        return false;
    }

    m_process = new QProcess(this);
    connect(m_process, &QProcess::started,         this, &MediaMtxManager::onProcessStarted);
    connect(m_process, &QProcess::readyReadStandardOutput, this, &MediaMtxManager::onReadyReadStdOut);
    connect(m_process, &QProcess::readyReadStandardError,  this, &MediaMtxManager::onReadyReadStdErr);
    connect(m_process,
            QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished),
            this, &MediaMtxManager::onProcessFinished);

    m_process->start(binary, {m_configPath});
    if (!m_process->waitForStarted(5000)) {
        m_lastError = "Failed to start mediamtx: " + m_process->errorString();
        delete m_process;
        m_process = nullptr;
        return false;
    }

    emit logMessage("[MediaMTX] Started on RTSP port " + QString::number(m_rtspPort));
    return true;
}

void MediaMtxManager::stop()
{
    if (!m_process) return;

    m_process->terminate();
    if (!m_process->waitForFinished(3000))
        m_process->kill();

    delete m_process;
    m_process = nullptr;

    // Remove temp config
    if (!m_configPath.isEmpty()) {
        QFile::remove(m_configPath);
        m_configPath.clear();
    }

    emit stopped();
    emit logMessage("[MediaMTX] Stopped.");
}

// ─────────────────────────────────────────────────────────────────────────────
QString MediaMtxManager::findMediaMtxBinary() const
{
    // 1. Next to the executable
    const QString appDir = QCoreApplication::applicationDirPath();
    const QStringList candidates = {
        appDir + "/mediamtx.exe",
        appDir + "/mediamtx",
        QDir::currentPath() + "/mediamtx.exe",
        QDir::currentPath() + "/mediamtx"
    };
    for (const QString &c : candidates)
        if (QFileInfo::exists(c)) return c;

    return {};
}

QString MediaMtxManager::generateConfig() const
{
    // Build a minimal MediaMTX YAML config.
    // Auth: separate publisher credentials (FFmpeg) vs. reader credentials (NVR clients).
    QString authBlock;
    if (!m_readUser.isEmpty()) {
        authBlock = QString(
            "authMethod: internal\n"
            "authInternalUsers:\n"
            "  - user: %1\n"
            "    pass: %2\n"
            "    permissions:\n"
            "      - action: read\n"
            "        path: \"\"\n"
            "  - user: %3\n"
            "    pass: %4\n"
            "    permissions:\n"
            "      - action: publish\n"
            "        path: \"\"\n"
        ).arg(m_readUser, m_readPass, m_pubUser, m_pubPass);
    } else {
        authBlock = "authMethod: no\n";
    }

    return QString(
        "# Auto-generated by IPCameraSimulator\n"
        "logLevel: warn\n"
        "logDestinations: [stdout]\n"
        "\n"
        "# Network\n"
        "rtspAddress: :%1\n"
        "rtmpDisable: yes\n"
        "hlsDisable: yes\n"
        "webrtcDisable: yes\n"
        "\n"
        "# API / metrics disabled\n"
        "api: no\n"
        "metrics: no\n"
        "pprof: no\n"
        "\n"
        "%2"
        "\n"
        "# Accept any path\n"
        "paths:\n"
        "  ~^.*$:\n"
        "    source: publisher\n"
    ).arg(m_rtspPort).arg(authBlock);
}

QString MediaMtxManager::writeConfigFile() const
{
    const QString tmpDir = QStandardPaths::writableLocation(QStandardPaths::TempLocation);
    const QString cfgPath = tmpDir + "/ipcamsim_mediamtx.yml";

    QFile file(cfgPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) return {};

    QTextStream ts(&file);
    ts << generateConfig();
    return cfgPath;
}

// ─────────────────────────────────────────────────────────────────────────────
void MediaMtxManager::onProcessStarted()
{
    emit started();
    emit logMessage("[MediaMTX] Process started (PID " +
                   QString::number(m_process->processId()) + ")");
}

void MediaMtxManager::onProcessFinished(int exitCode, QProcess::ExitStatus)
{
    emit logMessage("[MediaMTX] Process finished (exit " +
                   QString::number(exitCode) + ")");
    emit stopped();
}

void MediaMtxManager::onReadyReadStdOut()
{
    if (!m_process) return;
    const QString out = QString::fromUtf8(m_process->readAllStandardOutput()).trimmed();
    if (!out.isEmpty()) emit logMessage("[MediaMTX] " + out);
}

void MediaMtxManager::onReadyReadStdErr()
{
    if (!m_process) return;
    const QString err = QString::fromUtf8(m_process->readAllStandardError()).trimmed();
    if (!err.isEmpty()) emit logMessage("[MediaMTX] " + err);
}
